### ISSUE TITLE
Progress > 100%

### ISSUE THREAD

**Issue by rozetko** [CorpGlory/grafana-data-exporter#11]
After https://github.com/CorpGlory/grafana-data-exporter-panel/issues/6 progress is counted wrong, because it expects integral amount of days to export (from 00:00 of 1st day to 00:00 of 2nd day)
We should count progress differently
![image](https://user-images.githubusercontent.com/1989898/45896907-3c7cc780-bdde-11e8-8938-92fb949264df.png)

**Comment by jonyrock** [comment]
I think @sankerust can handle it.
